tap:
  - hashicorp/tap
  - homebrew/cask-versions

brew_upgrade_all: true
brew:
  # Command line tools
  - zoxide
  - thefuck
  - cheat
  - howdoi
  - tree
  - grep
  - less
  - findutils
  - gpg
  - pinentry-mac
  - watch
  - jq
  - jid
  - bat
  - qemu
  - openssh
  - htop
  # Programming languages
  - node
  - ruby
  - swift
  - go
  - scala
  - kotlin
  - rust
  - python
  - gcc
  #- name: octave
  # Programming tools
  - checkstyle
  - pmd
  - maven
  - gradle
  - ant
  - make
  - cmake
  - jenv
  - git
  - gh
  - diff-so-fancy
  - yuicompressor
  # Infrastructure tools
  - kind
  - helm
  - awscli
  - localstack/tap/localstack-cli
  - hashicorp/tap/terraform
  - opentofu
  - terraform-docs
  - hashicorp/tap/vault
  # Editors
  - nano
  # Download tools
  #- name: youtube-dl
  #- name: you-get
  - curl
  - wget
  # Backup tools
  #- name: duplicity
  #- name: syncthing
  # Services
  #- name: postgresql
  #- name: nginx
  # Scripting tools
  #- name: m-cli
  #- name: chrome-cli
  # Media tools
  - name: ffmpeg
    tags: media-apps
  - name: fprobe
    tags: media-apps
  - name: nmap
    tags: net-apps
  - name: netcat
    tags: net-apps
  - name: whois
    tags: net-apps
  - name: httpstat
    tags: net-apps
  - name: httpie
    tags: net-apps
  - name: binutils
    tags: os-dev-apps
  - name: coreutils
    tags: os-dev-apps
  # - name: jupmoreno/apps/crossyc
  #   tags: os-dev-apps
  - name: nasm
    tags: os-dev-apps

cask_upgrade_all: true
cask:
  # System utils
  - bartender
  #- bettertouchtool
  - karabiner-elements
  #- alfred
  - itsycal
  - gas-mask
  #- lumen
  - contexts
  - maccy
  - meetingbar
  # Utils
  - the-unarchiver
  - appcleaner
  - kap
  - iterm2
  - name: virtualbox
    arch: x86_64
  - name: virtualbox-extension-pack
    arch: x86_64
  #- unetbootin
  #- vnc-viewer
  #- teamviewer
  #- ovito
  #- balenaetcher
  #- android-file-transfer
  # Network tools
  - rapidapi
  - postman
  #- netspot
  #- wireshark
  # Devices
  - logitech-options
  # Securiry
  - 1password
  # Browsers
  - google-chrome
  - firefox
  - arc
  # Social
  - whatsapp
  #- telegram
  #- slack
  - discord
  - zoom
  # Develop
  - temurin8
  - temurin11
  - temurin17
  - temurin21
  - temurin
  - zed
  - visual-studio-code
  - jetbrains-toolbox
  - docker
  #- unity
  # Design
  #- sketch
  # Media
  #- vlc
  - iina
  - spotify
  #- handbrake
  #- audacity
  # Office
  - obsidian
  - microsoft-office
  #- calibre
  #- notion
  # Files
  #- dropbox
  #- google-drive
  - proton-drive
  - cyberduck
  #- transmission
  # Gaming
  - name: steam
    tags: gaming-apps
  - name: battle-net
    tags: gaming-apps
  - name: epic-games
    tags: gaming-apps
  - name: openemu
    tags: gaming-apps
  - name: sony-ps-remote-play
    tags: gaming-apps

mas_upgrade_all: true
mas:
  - 497799835 # Xcode
  - 441258766 # Magnet
  - 937984704 # Amphetamine
  #- 407963104 # Pixelmator
  - id: 409183694 # Keynote
    state: absent
  - id: 409201541 # Pages
    state: absent
  - id: 409203825 # Numbers
    state: absent
  - id: 682658836 # GarageBand
    state: absent

pip:

npm:
