- name: Link shared config
  ansible.builtin.file:
    src: '{{ role_path }}/files/{{ item.src }}'
    dest: '{{ ansible_user_dir }}/{{ item.dest }}'
    state: hard
  loop:
  - { src: "shellrc", dest: ".shellrc" }
  - { src: "kubectl_aliases", dest: ".config/shell/.kubectl_aliases" } # TODO: Move to a kubernetes role?

- name: Configure bash
  block:
  - name: Upgrade bash
    community.general.homebrew:
      name: bash
      state: latest
  - name: Install bash addons
    community.general.homebrew:
      name:
        - bash-preexec
        - bash-completion@2
      state: latest
  - name: Link configuration files
    ansible.builtin.file:
      src: '{{ role_path }}/files/{{ item.src }}'
      dest: '{{ ansible_user_dir }}/{{ item.dest }}'
      state: hard
    loop:
    - { src: "bashrc", dest: ".bashrc" }
    - { src: "bash_profile", dest: ".bash_profile" }
    - { src: "bash_sensible", dest: ".config/shell/.bash_sensible" }

- name: Configure zsh
  block:
  - name: Install zsh
    community.general.homebrew:
      name: zsh
      state: latest
  - name: Install zsh addons
    community.general.homebrew:
      name:
        - zsh-completions
      state: latest
  - name: Link configuration files
    ansible.builtin.file:
      src: '{{ role_path }}/files/{{ item.src }}'
      dest: '{{ ansible_user_dir }}/{{ item.dest }}'
      state: hard
    loop:
    - { src: "zshrc", dest: ".zshrc" }
    - { src: "zsh_plugins", dest: ".config/shell/.zsh_plugins" }

- name: "Set default terminal"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/zsh
  become: true

- name: Install and configure shell addons
  block:
  - name: Install shell theme
    block:
    - name: Install Starship
      community.general.homebrew:
        name: starship
        state: latest
    - name: Link configuration files
      ansible.builtin.file:
        src: '{{ role_path }}/files/{{ item.src }}'
        dest: '{{ ansible_user_dir }}/{{ item.dest }}'
        state: hard
      loop:
      - { src: "starship.toml", dest: ".config/shell/.starship.toml" }
  - name: Configure fzf
    block:        
    - name: Install fzf
      community.general.homebrew:
        name: fzf
        state: latest
    - name: Link fzf config
      ansible.builtin.file:
        src: '{{ role_path }}/files/{{ item.src }}'
        dest: '{{ ansible_user_dir }}/{{ item.dest }}'
        state: hard
      loop:
      - { src: "fzf.zsh", dest: ".config/shell/.fzf.zsh" }
      - { src: "fzf.bash", dest: ".config/shell/.fzf.bash" }
  - name: Configure atuin
    block:        
    - name: Install atuin
      community.general.homebrew:
        name: atuin
        state: latest
    - name: Link atuin config
      ansible.builtin.file:
        src: '{{ role_path }}/files/{{ item.src }}'
        dest: '{{ ansible_user_dir }}/{{ item.dest }}'
        state: hard
      loop:
      - { src: "atuin.toml", dest: ".config/shell/.atuin.toml" }
