- block:
  - name: Install brew app "{{ brew_item.name | default(brew_item) }}"
    community.general.homebrew:
      name: "{{ brew_item.name | default(brew_item) }}"
      state: latest
    register: output
  rescue:
  - name: Fail if error is not due to cask collision warning
    ansible.builtin.fail:
      msg: "{{ output.msg }}"
    when: output.msg is match('"Treating .* as a formula. For the cask, use .* or specify the `--cask` flag"')
  tags: "{{ brew_item.tags | default(omit) }}"
  when: brew_item is defined
