# TODO: Check brew installed
- include_tasks:
    file: tap.yml
    apply:
      tags:
        - brew
        - cask
  tags:
    - brew
    - cask

- include_tasks:
    file: brew.yml
    apply:
      tags:
        - brew
  loop: "{{ brew | default([]) }}"
  loop_control:
    loop_var: brew_item
  tags: brew

- include_tasks:
    file: cask.yml
    apply:
      tags:
        - cask
  loop: "{{ cask | default([]) }}"
  loop_control:
    loop_var: cask_item
  tags: cask

- include_tasks:
    file: mas.yml
    apply:
      tags:
        - mas
  loop: "{{ mas | default([]) }}"
  loop_control:
    loop_var: mas_item
  tags: mas

- include_tasks:
    file: pip.yml
    apply:
      tags:
        - pip
  loop: "{{ pip | default([]) }}"
  loop_control:
    loop_var: pip_item
  tags: pip

- include_tasks:
    file: npm.yml
    apply:
      tags:
        - npm
  loop: "{{ npm | default([]) }}"
  loop_control:
    loop_var: npm_item
  tags: npm

- include_tasks: 
    file: bin.yml
    apply:
      tags:
        - bin
  tags: bin

- name: Upgrade all brew apps
  community.general.homebrew:
    upgrade_all: true
  tags:
  - brew
  - update
  when: brew_upgrade_all

- name: Upgrade all cask apps
  community.general.homebrew_cask:
    upgrade_all: true
  tags:
  - cask
  - update
  when: cask_upgrade_all

- name: Upgrade all mas apps
  community.general.mas:
    upgrade_all: true
  tags:
  - mas
  - update
  when: mas_upgrade_all
